### ISSUE TITLE
ordering of bonuses

### ISSUE THREAD

**Issue by easchwar** [TheAxnJaxn/VinoBueno#2]
I would reorder some of your bonus material. Things like recommendations are really tricky. Companies spend tons of money paying really smart people to write algorithms to do this. We do not have this kind of time. Aim for low hanging fruit. I think the following are good choices:

avatars
image upload
typeahead

**Comment by TheAxnJaxn** [comment]
Another good point - swapped.

I was going to keep recommendations super simple - same varietal or type (red/white.)
